# Generated by Django 4.1.1 on 2022-10-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_contacto_ingredientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto", name="ingredientes", field=models.TextField(),
        ),
    ]
