# Generated by Django 4.1.1 on 2022-10-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_producto_ingredientes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto", old_name="ingredientes", new_name="descripcion",
        ),
    ]
