# Generated by Django 4.1.1 on 2022-11-02 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_ingredientes_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registro",
            fields=[
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("rut", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre_usario", models.CharField(max_length=20)),
                ("comuna", models.CharField(max_length=20)),
                ("telefono", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                (
                    "creacion_usr",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={"ordering": ["-rut"],},
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(null=True, upload_to="producto"),
        ),
    ]
